export const SET_REQUEST_ERROR = "SET_REQUEST_ERROR";
export const SET_REQUEST_SUCCESS = "SET_REQUEST_SUCCESS";
export const SET_REQUEST_PENDING = "SET_REQUEST_PENDING";
export const CREATE_REQUEST_SUCCESS="CREATE_REQUEST_SUCCESS"
export const UPDATE_REQUEST_SUCCESS="UPDATE_REQUEST_SUCCESS"
export const FETCH_USERS_SUCCESS="FETCH_USERS_SUCCESS"


