export const SET_CUSTOMER_ERROR = "SET_CUSTOMER_ERROR";
export const SET_CUSTOMER_SUCCESS = "SET_CUSTOMER_SUCCESS";
export const SET_CUSTOMER_PENDING = "SET_CUSTOMER_PENDING";
export const CREATE_CUSTOMER_SUCCESS="CREATE_CUSTOMER_SUCCESS"
export const UPDATE_CUSTOMER_SUCCESS="UPDATE_CUSTOMER_SUCCESS"
export const FETCH_ALL_CUSTOMERS_SUCCESS="FETCH_ALL_CUSTOMERS_SUCCESS"


