export const SET_USER_ERROR = "SET_USER_ERROR";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const SET_USER_PENDING = "SET_USER_PENDING";
export const CREATE_USER_SUCCESS="CREATE_USER_SUCCESS"
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS"

